package Prestador;


import DAO.CadastroPrestadoresDAO;
import DTO.CadastroPrestadoresDTO;
import P.I.Login;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

public class CadastroPrestadores extends javax.swing.JFrame {

    public CadastroPrestadores() {
        initComponents();
        
        ((PlainDocument) txtnome.getDocument()).setDocumentFilter(new LimiteCaracteres(50));
        ((PlainDocument) txttelefone.getDocument()).setDocumentFilter(new LimiteCaracteres(15));
        ((PlainDocument) txtcnpj.getDocument()).setDocumentFilter(new LimiteCaracteres(14));
        ((PlainDocument) txtemail.getDocument()).setDocumentFilter(new LimiteCaracteres(100));
        ((PlainDocument) txtendereco.getDocument()).setDocumentFilter(new LimiteCaracteres(100));
        ((PlainDocument) txtramo.getDocument()).setDocumentFilter(new LimiteCaracteres(100));
        ((PlainDocument) txtsenha.getDocument()).setDocumentFilter(new LimiteCaracteres(20));
        ((PlainDocument) txtsenha1.getDocument()).setDocumentFilter(new LimiteCaracteres(20));

        txttelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume(); // Bloqueia o caractere não numérico
                }
            }
        });
        txtcnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume(); // Bloqueia o caractere não numérico
                }
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcnpj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtramo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        enviar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();
        txtsenha1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("nome:");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 47, 37, -1));
        jPanel5.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 325, -1));

        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });
        jPanel5.add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 325, -1));

        jLabel2.setText("Telefone:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel5.add(txtcnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 325, -1));

        jLabel3.setText("Cnpj:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 37, -1));
        jPanel5.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 325, -1));

        jLabel4.setText("Email:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 37, -1));
        jPanel5.add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 325, -1));

        jLabel5.setText("Endereço:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 60, -1));
        jPanel5.add(txtramo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 325, -1));

        jLabel6.setText("Ramo:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 50, -1));

        jLabel7.setText("Senha:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 50, 20));

        jLabel8.setText("comfirmar:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 60, 20));

        enviar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        jPanel5.add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 350, 60));

        jLabel9.setText("Cadastro Clientes");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 350, 40));

        mostrar.setText("mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jPanel5.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));
        jPanel5.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 320, -1));
        jPanel5.add(txtsenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 320, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 470, 480));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(571, 571, 571)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(843, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed

        // Captura os valores dos campos
        String nome = txtnome.getText().trim();
        String telefone = txttelefone.getText().trim();
        String cnpj = txtcnpj.getText().trim();
        String email = txtemail.getText().trim();
        String endereco = txtendereco.getText().trim();
        String ramo = txtramo.getText().trim();
        String senha = txtsenha.getText().trim();
        String senha1 = txtsenha1.getText().trim();

        boolean camposValidos = true;

        // Função para validar e pintar campo vazio
        if (nome.isEmpty()) {
            txtnome.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtnome.setBackground(Color.WHITE);
        }

        if (telefone.isEmpty()) {
            txttelefone.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txttelefone.setBackground(Color.WHITE);
        }

        if (cnpj.isEmpty()) {
            txtcnpj.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtcnpj.setBackground(Color.WHITE);
        }

        if (email.isEmpty()) {
            txtemail.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtemail.setBackground(Color.WHITE);
        }

        if (endereco.isEmpty()) {
            txtendereco.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtendereco.setBackground(Color.WHITE);
        }

        if (ramo.isEmpty()) {
            txtramo.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtramo.setBackground(Color.WHITE);
        }

        if (senha.isEmpty()) {
            txtsenha.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtsenha.setBackground(Color.WHITE);
        }

        if (senha1.isEmpty()) {
            txtsenha1.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtsenha1.setBackground(Color.WHITE);
        }

        if (!camposValidos) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
            return;
        }

        // Verifica se as senhas coincidem
        if (!senha.equals(senha1)) {
            txtsenha.setBackground(Color.PINK);
            txtsenha1.setBackground(Color.PINK);
            JOptionPane.showMessageDialog(null, "As senhas não coincidem!");
            return;
        }

        // Cadastro
        CadastroPrestadoresDTO objfprestadores = new CadastroPrestadoresDTO();
        objfprestadores.setNome(nome);
        objfprestadores.setTelefone(telefone);
        objfprestadores.setCnpj(cnpj);
        objfprestadores.setEmail(email);
        objfprestadores.setEndereco(endereco);
        objfprestadores.setRamo(ramo);
        objfprestadores.setSenha(senha);

        CadastroPrestadoresDAO objPrestadoresdao = new CadastroPrestadoresDAO();

        try {
            objPrestadoresdao.cadastrarPrestador(objfprestadores);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
            Login login = new Login();
            login.setVisible(true);
            this.setVisible(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + erro.getMessage());
        }


    }//GEN-LAST:event_enviarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginPrestadores logi = new LoginPrestadores();
        logi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed

    }//GEN-LAST:event_txttelefoneActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        if (txtsenha.getEchoChar() != (char) 0) {
            // Mostrar a senha
            txtsenha.setEchoChar((char) 0);
            txtsenha1.setEchoChar((char) 0);
            mostrar.setText("Ocultar"); // Altera o texto do botão
        } else {
            // Esconder a senha novamente
            txtsenha.setEchoChar('*'); // Ou '*'
            txtsenha1.setEchoChar('*');
            mostrar.setText("Mostrar");
        }
    }//GEN-LAST:event_mostrarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPrestadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPrestadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPrestadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPrestadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPrestadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField txtcnpj;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtramo;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JPasswordField txtsenha1;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables

    private void CarregarCampos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setDados(String id, String nome, String telefone, String cpf, String rg, String cidade, String email, String senha) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private boolean validarSenhas() {
        String senha1 = txtsenha.getText();
        String senha2 = txtsenha1.getText();

        if (!senha1.equals(senha2)) {
            // Define a borda vermelha se estiver diferente
            txtsenha.setBackground(Color.PINK);
            txtsenha1.setBackground(Color.PINK);
            JOptionPane.showMessageDialog(null, "As senhas não coincidem.");
            return false;
        } else {
            // Volta para a cor normal se estiverem iguais
            txtsenha.setBackground(Color.WHITE);
            txtsenha1.setBackground(Color.WHITE);
            return true;
        }
    }

    class LimiteCaracteres extends DocumentFilter {

        private int limite;

        public LimiteCaracteres(int limite) {
            this.limite = limite;
        }

        @Override
        public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr)
                throws BadLocationException {
            if ((fb.getDocument().getLength() + string.length()) <= limite) {
                super.insertString(fb, offset, string, attr);
            }
        }

        @Override
        public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                throws BadLocationException {
            if ((fb.getDocument().getLength() - length + text.length()) <= limite) {
                super.replace(fb, offset, length, text, attrs);
            }
        }

    }
}
