package P.I;

import DAO.CadastroClientesDAO;
import DTO.CadastroClientesDTO;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

public class TelaEditarClientes extends javax.swing.JFrame {

    public TelaEditarClientes() {
        initComponents();
        ((PlainDocument) txtnome.getDocument()).setDocumentFilter(new LimiteCaracteres(50)); 
        ((PlainDocument) txtTelefone.getDocument()).setDocumentFilter(new LimiteCaracteres(15)); 
        ((PlainDocument) txtcidade.getDocument()).setDocumentFilter(new LimiteCaracteres(14)); 
        ((PlainDocument) txtcpf.getDocument()).setDocumentFilter(new LimiteCaracteres(12));
        ((PlainDocument) txtemail.getDocument()).setDocumentFilter(new LimiteCaracteres(100)); 
        ((PlainDocument) txtrg.getDocument()).setDocumentFilter(new LimiteCaracteres(100)); 
        ((PlainDocument) txtsenha.getDocument()).setDocumentFilter(new LimiteCaracteres(20)); 
        ((PlainDocument) txtsenha1.getDocument()).setDocumentFilter(new LimiteCaracteres(20)); 
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); 
        }
    }
});
         txtcpf.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); 
        }
    }
    
});
 txtrg.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); // Bloqueia o caractere não numérico
        }
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtrg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        alterar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        txtsenha1 = new javax.swing.JPasswordField();
        txtsenha = new javax.swing.JPasswordField();
        mostrar = new javax.swing.JButton();
        txtid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("nome:");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 47, 37, -1));

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        jPanel5.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 325, -1));

        jLabel2.setText("Telefone:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });
        jPanel5.add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 325, -1));

        jLabel3.setText("Cpf:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 37, -1));
        jPanel5.add(txtrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 325, -1));

        jLabel4.setText("RG:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 37, -1));
        jPanel5.add(txtcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 325, -1));

        jLabel5.setText("Cidade:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 50, -1));
        jPanel5.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 325, -1));

        jLabel6.setText("email:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 50, -1));

        jLabel7.setText("senha:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 50, 20));

        jLabel8.setText("comfirmar:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 60, 20));

        alterar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        jPanel5.add(alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 350, 60));

        jLabel9.setText("Cadastro Clientes");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 350, 40));

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        jPanel5.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 330, -1));

        txtsenha1.setText("jPasswordField1");
        jPanel5.add(txtsenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 320, -1));
        jPanel5.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 320, -1));

        mostrar.setText("mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jPanel5.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 480));

        txtid.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(852, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(390, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed

        // Captura os valores dos campos
        String nome = txtnome.getText().trim();
        String telefone = txtTelefone.getText().trim();
        String cpf = txtcpf.getText().trim();
        String rg = txtrg.getText().trim();
        String cidade = txtcidade.getText().trim();
        String email = txtemail.getText().trim();
        String senha = txtsenha.getText().trim();
        String senha1 = txtsenha1.getText().trim();

        boolean camposValidos = true;

        // Validação de campos obrigatórios
        if (nome.isEmpty()) {
            txtnome.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtnome.setBackground(Color.WHITE);
        }

        if (telefone.isEmpty()) {
            txtTelefone.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtTelefone.setBackground(Color.WHITE);
        }

        if (cpf.isEmpty()) {
            txtcpf.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtcpf.setBackground(Color.WHITE);
        }

        if (rg.isEmpty()) {
            txtrg.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtrg.setBackground(Color.WHITE);
        }

        if (cidade.isEmpty()) {
            txtcidade.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtcidade.setBackground(Color.WHITE);
        }

        if (email.isEmpty()) {
            txtemail.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtemail.setBackground(Color.WHITE);
        }

        if (senha.isEmpty()) {
            txtsenha.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtsenha.setBackground(Color.WHITE);
        }

        if (senha1.isEmpty()) {
            txtsenha1.setBackground(Color.PINK);
            camposValidos = false;
        } else {
            txtsenha1.setBackground(Color.WHITE);
        }

        // Verifica campos obrigatórios
        if (!camposValidos) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
            return;
        }

        // Verifica se as senhas coincidem
        if (!senha.equals(senha1)) {
            txtsenha.setBackground(Color.PINK);
            txtsenha1.setBackground(Color.PINK);
            JOptionPane.showMessageDialog(null, "As senhas não coincidem.");
            return;
        } else {
            txtsenha.setBackground(Color.WHITE);
            txtsenha1.setBackground(Color.WHITE);
        }

        // Se tudo estiver válido, prossegue com alteração
        try {
            alterarClientes(); // método que altera os dados
            JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso!");

            // Abre a tela de visualização
            VisualizarClientes Cadastro = new VisualizarClientes();
            Cadastro.setVisible(true);
            this.setVisible(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Falha na alteração: " + erro.getMessage());
        }


    }//GEN-LAST:event_alterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VisualizarClientes visul = new VisualizarClientes();
        visul.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed


    }//GEN-LAST:event_txtnomeActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        if (txtsenha.getEchoChar() != (char) 0) {
            // Mostrar a senha
            txtsenha.setEchoChar((char) 0);
            txtsenha1.setEchoChar((char) 0);
            mostrar.setText("Ocultar"); // Altera o texto do botão
        } else {
            // Esconder a senha novamente
            txtsenha.setEchoChar('*'); // Ou '*'
            txtsenha1.setEchoChar('*');
            mostrar.setText("Mostrar");
        }

    }//GEN-LAST:event_mostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtrg;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JPasswordField txtsenha1;
    // End of variables declaration//GEN-END:variables

    public void setDados(String id, String nome, String telefone, String cpf, String rg, String cidade, String email, String senha) {
        txtid.setText(id);
        txtnome.setText(nome);
        txtTelefone.setText(telefone);
        txtcpf.setText(cpf);
        txtrg.setText(rg);
        txtcidade.setText(cidade);
        txtemail.setText(email);
        txtsenha.setText(senha);
        txtsenha1.setText(senha);
    }

    private void alterarClientes() {
        int idClientes;
        String nome, telefone, cpf, rg, cidade, email, senha;
        idClientes = Integer.parseInt(txtid.getText());
        nome = txtnome.getText();
        telefone = txtTelefone.getText();
        cpf = txtcpf.getText();
        rg = txtrg.getText();
        cidade = txtcidade.getText();
        email = txtemail.getText();
        senha = txtsenha.getText();
        senha = txtsenha1.getText();
        CadastroClientesDTO objCadastroClientesdto = new CadastroClientesDTO();
        objCadastroClientesdto.setIdClientes(idClientes);
        objCadastroClientesdto.setNome(nome);
        objCadastroClientesdto.setTelefone(telefone);
        objCadastroClientesdto.setCpf(cpf);
        objCadastroClientesdto.setRg(rg);
        objCadastroClientesdto.setCidade(cidade);
        objCadastroClientesdto.setEmail(email);
        objCadastroClientesdto.setSenha(senha);

        CadastroClientesDAO objCadastroClientesdao = new CadastroClientesDAO();
        objCadastroClientesdao.alterarClientes(objCadastroClientesdto);

    }

    private boolean validarSenhas() {
        String senha1 = txtsenha.getText();
        String senha2 = txtsenha1.getText();

        if (!senha1.equals(senha2)) {
            // Define a borda vermelha se estiver diferente
            txtsenha.setBackground(Color.PINK);
            txtsenha1.setBackground(Color.PINK);
            JOptionPane.showMessageDialog(null, "As senhas não coincidem.");
            return false;
        } else {
            // Volta para a cor normal se estiverem iguais
            txtsenha.setBackground(Color.WHITE);
            txtsenha1.setBackground(Color.WHITE);
            return true;
        }
    }

    class LimiteCaracteres extends DocumentFilter {

        private int limite;

        public LimiteCaracteres(int limite) {
            this.limite = limite;
        }

        @Override
        public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr)
                throws BadLocationException {
            if ((fb.getDocument().getLength() + string.length()) <= limite) {
                super.insertString(fb, offset, string, attr);
            }
        }

        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                throws BadLocationException {
            if ((fb.getDocument().getLength() - length + text.length()) <= limite) {
                super.replace(fb, offset, length, text, attrs);
            }
        }
        
    }
}
